server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
          - Path=${app.api-prefix}/auth-service/**
          filters:
          - StripPrefix=2
        - id: course-service
          uri: http://localhost:8082
          predicates:
          - Path=${app.api-prefix}/profile-service/**
          filters:
          - StripPrefix=2
        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/notification-service/**
          filters:
            - StripPrefix=2